import { P } from "./patch-kit";
import { stepsFromCode } from "./arp";
import { SHAPE_PRESETS, defaultDrawShape, defaultDrawShape2, type DrawShape } from "./draw-shape";
import type { Patch } from "./types";

function sh(id: string, extra: Partial<DrawShape> = {}): DrawShape {
  const pr = SHAPE_PRESETS.find((x) => x.id === id);
  const points = extra.points ?? (pr ? pr.points() : defaultDrawShape().points);
  return {
    ...defaultDrawShape(),
    on: true,
    preset: id,
    from: pr?.from ?? 0.15,
    ...extra,
    points,
  };
}

function sh2(id: string, extra: Partial<DrawShape> = {}): DrawShape {
  return { ...defaultDrawShape2(), ...sh(id, extra) };
}

/** 50 singles for Mk V.7 — Shape, dual LFO clocks, own FX/arp/poly. */
export const EXTRA_V57: Patch[] = [
  P("Pad", "v57-silk-wake", "Silk Wake", {
    osc1: { wave: "sawtooth", level: 0.72 },
    osc2: { wave: "sawtooth", fine: 9, level: 0.68 },
    subLevel: 0.12,
    drift: 0.16,
    ampEnv: { attack: 0.08, decay: 0.6, sustain: 0.82, release: 2.2 },
    lfo: { rate: 0.07, depth: 0.12, dest: "cutoff", wave: "sine" },
    lfo2: { rate: 0.11, depth: 0.18, dest: "pan", wave: "triangle" },
    fx: { delayMix: 0.12, delayTime: 0.42, delayFeedback: 0.22, reverbMix: 0.38, chorusMix: 0.22, phaserMix: 0.06 },
    drawShape: sh("silk", { dest: "amp", time: 4.2, depth: 0.92 }),
    drawShape2: sh2("glow", { dest: "cutoff", time: 5.5, depth: 0.45 }),
  }),
  P("Pad", "v57-glow-room", "Glow Room", {
    osc1: { wave: "triangle", level: 0.7 },
    osc2: { wave: "sawtooth", fine: 11, octave: 1, level: 0.4 },
    ampEnv: { attack: 0.9, decay: 1, sustain: 0.78, release: 2.6 },
    filter: { cutoff: 0.4, resonance: 0.22, envAmount: 0.18 },
    lfo: { rate: 0.05, depth: 0.2, dest: "cutoff" },
    lfo2: { rate: 0.08, depth: 0.14, dest: "pan" },
    fx: { delayMix: 0.18, delayTime: 0.5, delayFeedback: 0.28, reverbMix: 0.48, chorusMix: 0.16, phaserMix: 0.12 },
    drawShape: sh("glow", { dest: "amp", dest2: "cutoff", time: 6, depth: 0.88 }),
  }),
  P("Pad", "v57-bloom-choir", "Bloom Choir", {
    osc1: { wave: "wt", table: "vocal", pwm: 0.28, level: 0.74 },
    osc2: { wave: "wt", table: "vowel", pwm: 0.55, fine: 6, level: 0.55 },
    unison: { voices: 2, detune: 0.18, spread: 0.55 },
    ampEnv: { attack: 0.7, decay: 0.8, sustain: 0.8, release: 2.4 },
    lfo: { rate: 0.06, depth: 0.16, dest: "cutoff" },
    lfo2: { rate: 0.09, depth: 0.12, dest: "pan" },
    fx: { delayMix: 0.14, reverbMix: 0.46, chorusMix: 0.2, delayTime: 0.4, delayFeedback: 0.22, phaserMix: 0.08 },
    drawShape: sh("silk", { dest: "amp", time: 5, depth: 0.9 }),
  }),
  P("Pad", "v57-rush-cloud", "Rush Cloud", {
    osc1: { wave: "supersaw", level: 0.62 },
    osc2: { wave: "triangle", octave: 1, level: 0.28 },
    filter: { cutoff: 0.36, resonance: 0.18, envAmount: 0.28 },
    ampEnv: { attack: 0.05, decay: 0.4, sustain: 0.75, release: 1.8 },
    fx: { delayMix: 0.16, reverbMix: 0.4, chorusMix: 0.28, delayTime: 0.36, delayFeedback: 0.24, phaserMix: 0.1 },
    drawShape: sh("rush", { dest: "amp", dest2: "cutoff", time: 3.6, depth: 1 }),
  }),
  P("Pad", "v57-hold-horizon", "Hold Horizon", {
    osc1: { wave: "sawtooth", level: 0.68 },
    osc2: { wave: "square", pwm: 0.4, fine: 5, level: 0.4 },
    ampEnv: { attack: 0.02, decay: 0.3, sustain: 0.88, release: 2 },
    lfo2: { rate: 0.07, depth: 0.2, dest: "pan" },
    fx: { delayMix: 0.1, reverbMix: 0.44, chorusMix: 0.18, delayTime: 0.48, delayFeedback: 0.2, phaserMix: 0 },
    drawShape: sh("hold", { dest: "amp", time: 2.4, depth: 0.8, from: 0 }),
  }),
  P("Pad", "v57-arc-nave", "Arc Nave", {
    osc1: { wave: "wt", table: "organ", pwm: 0.35, level: 0.7 },
    osc2: { wave: "sine", octave: 1, level: 0.3 },
    ampEnv: { attack: 0.6, decay: 0.7, sustain: 0.8, release: 3 },
    fx: { delayMix: 0.12, reverbMix: 0.52, chorusMix: 0.12, delayTime: 0.55, delayFeedback: 0.22, phaserMix: 0.06 },
    drawShape: sh("arc", { dest: "amp", mode: "loop", time: 8, depth: 0.55, from: 0 }),
  }),
  P("Pad", "v57-night-silk", "Night Silk", {
    osc1: { wave: "triangle", level: 0.65 },
    osc2: { wave: "sawtooth", octave: -1, level: 0.45 },
    filter: { type: "lowpass", cutoff: 0.32, resonance: 0.28, envAmount: 0.2 },
    lfo: { rate: 0.04, depth: 0.22, dest: "cutoff" },
    lfo2: { rate: 0.13, depth: 0.16, dest: "pan" },
    fx: { delayMix: 0.2, reverbMix: 0.5, chorusMix: 0.1, delayTime: 0.52, delayFeedback: 0.3, phaserMix: 0.16 },
    drawShape: sh("silk", { dest: "amp", time: 6.5, depth: 0.95 }),
  }),
  P("Pad", "v57-vowel-bloom", "Vowel Bloom", {
    osc1: { wave: "wt", table: "vowel", pwm: 0.22, level: 0.78 },
    osc2: { wave: "wt", table: "formant", pwm: 0.7, fine: 8, level: 0.5 },
    lfo: { rate: 0.08, depth: 0.28, dest: "cutoff" },
    lfo2: { rate: 0.05, depth: 0.12, dest: "cutoff" },
    ampEnv: { attack: 0.5, decay: 0.8, sustain: 0.76, release: 2 },
    fx: { delayMix: 0.15, reverbMix: 0.4, chorusMix: 0.14, delayTime: 0.38, delayFeedback: 0.24, phaserMix: 0.1 },
    drawShape: sh("silk", { dest: "pwm", dest2: "amp", time: 4.8, depth: 0.7 }),
  }),
  P("Pad", "v57-frozen-lift", "Frozen Lift", {
    osc1: { wave: "sine", level: 0.55 },
    osc2: { wave: "triangle", octave: 1, fine: 5, level: 0.5 },
    filter: { type: "highpass", cutoff: 0.22, resonance: 0.2, envAmount: 0.15, slope: 12 },
    fx: { delayMix: 0.22, reverbMix: 0.46, chorusMix: 0.08, delayTime: 0.6, delayFeedback: 0.28, phaserMix: 0.2 },
    drawShape: sh("lift", { dest: "cutoff", dest2: "amp", time: 7, depth: 0.8 }),
  }),
  P("Pad", "v57-air-silk", "Air Silk", {
    osc1: { wave: "sawtooth", level: 0.58 },
    osc2: { wave: "triangle", octave: 2, level: 0.22 },
    noiseLevel: 0.06,
    ampEnv: { attack: 1.1, decay: 0.9, sustain: 0.7, release: 2.8 },
    lfo2: { rate: 0.09, depth: 0.22, dest: "pan" },
    fx: { delayMix: 0.18, reverbMix: 0.54, chorusMix: 0.16, delayTime: 0.48, delayFeedback: 0.22, phaserMix: 0.14 },
    drawShape: sh("silk", { dest: "amp", time: 5.5, depth: 1 }),
  }),

  P("Bass", "v57-iron-sub", "Iron Sub", {
    osc1: { wave: "sine", octave: -2, level: 1 },
    osc2: { wave: "triangle", octave: -1, level: 0.28 },
    subLevel: 0.85,
    drive: 0.16,
    polyMode: "mono",
    glide: 0.06,
    filter: { cutoff: 0.28, resonance: 0.12, envAmount: 0.22 },
    ampEnv: { attack: 0.004, decay: 0.22, sustain: 0.82, release: 0.14 },
    fx: { delayMix: 0, reverbMix: 0.03, chorusMix: 0, delayTime: 0.2, delayFeedback: 0, phaserMix: 0 },
  }),
  P("Bass", "v57-porta-rubber", "Porta Rubber", {
    osc1: { wave: "triangle", octave: -1, level: 0.95 },
    osc2: { wave: "sawtooth", octave: -1, fine: 4, level: 0.3 },
    subLevel: 0.7,
    polyMode: "legato",
    glide: 0.18,
    drive: 0.2,
    filter: { cutoff: 0.34, resonance: 0.22, envAmount: 0.3 },
    fx: { delayMix: 0.02, reverbMix: 0.05, chorusMix: 0, delayTime: 0.2, delayFeedback: 0, phaserMix: 0 },
  }),
  P("Bass", "v57-click-sub", "Click Sub", {
    osc1: { wave: "sine", octave: -2, level: 0.95 },
    osc2: { wave: "square", octave: 1, pwm: 0.2, level: 0.08 },
    noiseLevel: 0.12,
    subLevel: 0.8,
    polyMode: "mono",
    glide: 0.04,
    ampEnv: { attack: 0.001, decay: 0.18, sustain: 0.7, release: 0.12 },
    filterEnv: { attack: 0.001, decay: 0.08, sustain: 0.05, release: 0.06 },
    fx: { delayMix: 0, reverbMix: 0.02, chorusMix: 0, delayTime: 0.2, delayFeedback: 0, phaserMix: 0 },
  }),
  P("Bass", "v57-fifth-bass", "Fifth Bass", {
    osc1: { wave: "sawtooth", octave: -1, level: 0.88 },
    osc2: { wave: "sawtooth", octave: -1, semitone: 7, level: 0.45 },
    subLevel: 0.55,
    polyMode: "legato",
    glide: 0.05,
    drive: 0.24,
    filter: { cutoff: 0.38, resonance: 0.28, envAmount: 0.4 },
    fx: { delayMix: 0.04, reverbMix: 0.06, chorusMix: 0, delayTime: 0.22, delayFeedback: 0.1, phaserMix: 0 },
  }),
  P("Bass", "v57-pwm-sub", "PWM Sub", {
    osc1: { wave: "pulse", octave: -1, pwm: 0.28, level: 0.9 },
    osc2: { wave: "pulse", octave: -1, pwm: 0.62, fine: 3, level: 0.35 },
    subLevel: 0.6,
    polyMode: "mono",
    lfo: { rate: 0.35, depth: 0.22, dest: "cutoff", wave: "triangle" },
    fx: { delayMix: 0.03, reverbMix: 0.05, chorusMix: 0, delayTime: 0.2, delayFeedback: 0, phaserMix: 0 },
    drawShape: sh("pluck", { dest: "pwm", time: 0.8, depth: 0.4, from: 0 }),
  }),
  P("Bass", "v57-vel-floor", "Vel Floor", {
    osc1: { wave: "sawtooth", octave: -1, level: 0.92 },
    osc2: { wave: "square", octave: -1, level: 0.22 },
    subLevel: 0.65,
    velFilt: 0.7,
    polyMode: "mono",
    filter: { cutoff: 0.26, resonance: 0.42, envAmount: 0.55 },
    fx: { delayMix: 0.02, reverbMix: 0.04, chorusMix: 0, delayTime: 0.2, delayFeedback: 0, phaserMix: 0 },
  }),
  P("Bass", "v57-acid-dry", "Acid Dry", {
    osc1: { wave: "sawtooth", octave: -1, level: 1 },
    osc2: { wave: "square", octave: -1, pwm: 0.3, level: 0.18 },
    drive: 0.36,
    polyMode: "legato",
    glide: 0.07,
    filter: { cutoff: 0.3, resonance: 0.72, envAmount: 0.7 },
    fx: { delayMix: 0.06, reverbMix: 0.04, chorusMix: 0, delayTime: 0.22, delayFeedback: 0.18, phaserMix: 0 },
    arp: { on: false, mode: "up", rate: "1/16", octaves: 1, gate: 0.6, swing: 0.06, tempo: 128 },
  }),
  P("Bass", "v57-808-tail", "808 Tail", {
    osc1: { wave: "sine", octave: -2, level: 1 },
    osc2: { wave: "sine", octave: -1, level: 0.15 },
    subLevel: 0.92,
    polyMode: "mono",
    glide: 0.2,
    ampEnv: { attack: 0.002, decay: 0.85, sustain: 0.08, release: 0.45 },
    fx: { delayMix: 0, reverbMix: 0.06, chorusMix: 0, delayTime: 0.2, delayFeedback: 0, phaserMix: 0 },
  }),

  P("Lead", "v57-delay-knife", "Delay Knife", {
    osc1: { wave: "sawtooth", level: 0.9 },
    osc2: { wave: "square", pwm: 0.35, fine: 6, level: 0.35 },
    polyMode: "legato",
    glide: 0.1,
    drive: 0.22,
    filter: { cutoff: 0.55, resonance: 0.22, envAmount: 0.28 },
    lfo: { rate: 0.22, depth: 0.1, dest: "cutoff" },
    lfo2: { rate: 4.5, depth: 0.06, dest: "pitch", wave: "sine" },
    fx: { delayMix: 0.32, delayTime: 0.28, delayFeedback: 0.38, reverbMix: 0.1, chorusMix: 0.08, phaserMix: 0.04 },
  }),
  P("Lead", "v57-pwm-cry", "PWM Cry", {
    osc1: { wave: "pulse", pwm: 0.22, level: 0.92 },
    osc2: { wave: "pulse", pwm: 0.7, fine: 4, level: 0.4 },
    polyMode: "legato",
    glide: 0.12,
    lfo: { rate: 0.4, depth: 0.18, dest: "cutoff", wave: "triangle" },
    fx: { delayMix: 0.2, delayTime: 0.32, delayFeedback: 0.3, reverbMix: 0.12, chorusMix: 0.06, phaserMix: 0 },
    drawShape: sh("warp", { dest: "pwm", mode: "loop", time: 2.4, depth: 0.55, from: 0 }),
  }),
  P("Lead", "v57-super-thin", "Super Thin", {
    osc1: { wave: "supersaw", level: 0.7 },
    osc2: { wave: "triangle", octave: 1, level: 0.2 },
    unison: { voices: 3, detune: 0.16, spread: 0.62 },
    polyMode: "poly",
    filter: { cutoff: 0.62, slope: 12, resonance: 0.12, envAmount: 0.2 },
    fx: { delayMix: 0.16, reverbMix: 0.16, chorusMix: 0.32, delayTime: 0.3, delayFeedback: 0.22, phaserMix: 0.08 },
  }),
  P("Lead", "v57-glide-fifth", "Glide Fifth", {
    osc1: { wave: "sawtooth", level: 0.85 },
    osc2: { wave: "sawtooth", semitone: 7, level: 0.5 },
    polyMode: "legato",
    glide: 0.22,
    fx: { delayMix: 0.18, delayTime: 0.36, delayFeedback: 0.28, reverbMix: 0.14, chorusMix: 0.12, phaserMix: 0.06 },
  }),
  P("Lead", "v57-talk-formant", "Talk Formant", {
    osc1: { wave: "wt", table: "formant", pwm: 0.3, level: 0.88 },
    osc2: { wave: "wt", table: "vocal", pwm: 0.62, fine: 5, level: 0.4 },
    polyMode: "legato",
    glide: 0.08,
    lfo: { rate: 0.28, depth: 0.32, dest: "cutoff", wave: "sine" },
    lfo2: { rate: 5.5, depth: 0.05, dest: "pitch" },
    fx: { delayMix: 0.14, reverbMix: 0.12, chorusMix: 0.08, delayTime: 0.28, delayFeedback: 0.22, phaserMix: 0.1 },
  }),
  P("Lead", "v57-sync-howl", "Sync Howl", {
    osc1: { wave: "sawtooth", level: 0.9 },
    osc2: { wave: "square", octave: 1, level: 0.35 },
    sync: 0.45,
    polyMode: "mono",
    glide: 0.14,
    drive: 0.3,
    lfo: { rate: 0.18, depth: 0.25, dest: "cutoff" },
    fx: { delayMix: 0.22, delayTime: 0.3, delayFeedback: 0.34, reverbMix: 0.1, chorusMix: 0.05, phaserMix: 0.08 },
  }),
  P("Lead", "v57-halo-delay", "Halo Delay", {
    osc1: { wave: "triangle", level: 0.8 },
    osc2: { wave: "sine", octave: 1, fine: 8, level: 0.4 },
    polyMode: "poly",
    fx: { delayMix: 0.38, delayTime: 0.34, delayFeedback: 0.42, reverbMix: 0.18, chorusMix: 0.22, phaserMix: 0.1 },
    drawShape: sh("silk", { dest: "amp", time: 1.6, depth: 0.45 }),
  }),

  P("Sequence", "v57-gate-arp", "Gate Arp", {
    osc1: { wave: "square", pwm: 0.32, level: 0.82 },
    osc2: { wave: "sawtooth", octave: 1, level: 0.3 },
    arp: { on: true, hold: true, mode: "up", rate: "1/16", octaves: 2, gate: 0.7, swing: 0.08, tempo: 126 },
    fx: { delayMix: 0.2, delayTime: 0.25, delayFeedback: 0.32, reverbMix: 0.12, chorusMix: 0.08, phaserMix: 0 },
    drawShape: sh("gate", { dest: "amp", mode: "loop", time: 0.5, depth: 0.85, from: 0 }),
  }),
  P("Sequence", "v57-chop-seq", "Chop Seq", {
    osc1: { wave: "sawtooth", level: 0.85 },
    osc2: { wave: "pulse", pwm: 0.4, octave: -1, level: 0.28 },
    arp: { on: true, hold: true, pattern: true, mode: "up", rate: "1/16", octaves: 1, gate: 0.55, swing: 0.1, tempo: 130, steps: stepsFromCode("x.xx.x.x.xx.x.x.") },
    fx: { delayMix: 0.16, reverbMix: 0.1, chorusMix: 0.06, delayTime: 0.22, delayFeedback: 0.28, phaserMix: 0 },
    drawShape: sh("chop", { dest: "amp", mode: "loop", time: 0.8, depth: 0.7, from: 0 }),
  }),
  P("Keys", "v57-trem-keys", "Trem Keys", {
    osc1: { wave: "sawtooth", level: 0.72 },
    osc2: { wave: "triangle", fine: 7, level: 0.5 },
    ampEnv: { attack: 0.01, decay: 0.28, sustain: 0.7, release: 0.4 },
    lfo: { rate: 5.8, depth: 0.08, dest: "pitch" },
    lfo2: { rate: 0.22, depth: 0.12, dest: "pan" },
    fx: { delayMix: 0.1, reverbMix: 0.2, chorusMix: 0.18, delayTime: 0.3, delayFeedback: 0.18, phaserMix: 0.06 },
    drawShape: sh("trem", { dest: "amp", mode: "loop", time: 0.7, depth: 0.55, from: 0 }),
  }),
  P("Sequence", "v57-held-minor", "Held Minor", {
    osc1: { wave: "square", pwm: 0.38, level: 0.8 },
    osc2: { wave: "sawtooth", octave: 1, level: 0.28 },
    arp: { on: true, hold: true, mode: "updown", rate: "1/16", octaves: 2, gate: 0.48, swing: 0.06, tempo: 118, pattern: true, steps: stepsFromCode("xxxxuuuuddddxxxx") },
    fx: { delayMix: 0.22, reverbMix: 0.14, chorusMix: 0.1, delayTime: 0.26, delayFeedback: 0.3, phaserMix: 0.04 },
  }),
  P("Sequence", "v57-pulse-seq", "Pulse Seq", {
    osc1: { wave: "pulse", pwm: 0.3, level: 0.85 },
    osc2: { wave: "sine", octave: 2, level: 0.2 },
    arp: { on: true, hold: true, mode: "up", rate: "1/8", octaves: 1, gate: 0.4, swing: 0.16, tempo: 122 },
    fx: { delayMix: 0.18, reverbMix: 0.1, chorusMix: 0.05, delayTime: 0.3, delayFeedback: 0.26, phaserMix: 0 },
    drawShape: sh("pulse", { dest: "amp", mode: "loop", time: 0.45, depth: 0.8, from: 0 }),
  }),
  P("Sequence", "v57-zig-arp", "Zig Arp", {
    osc1: { wave: "sawtooth", level: 0.82 },
    osc2: { wave: "square", octave: 1, level: 0.25 },
    arp: { on: true, hold: true, mode: "random", rate: "1/16", octaves: 2, gate: 0.38, swing: 0, tempo: 128 },
    fx: { delayMix: 0.24, reverbMix: 0.12, chorusMix: 0.08, delayTime: 0.22, delayFeedback: 0.34, phaserMix: 0.08 },
    drawShape: sh("zig", { dest: "cutoff", mode: "loop", time: 1.2, depth: 0.5, from: 0 }),
  }),
  P("Sequence", "v57-step-pat", "Step Pattern", {
    osc1: { wave: "square", pwm: 0.45, level: 0.84 },
    osc2: { wave: "triangle", octave: -1, level: 0.3 },
    arp: { on: true, hold: true, pattern: true, mode: "up", rate: "1/16", octaves: 1, gate: 0.5, swing: 0.12, tempo: 124, steps: stepsFromCode("xx.xx.x.xx.xx.x.") },
    fx: { delayMix: 0.14, reverbMix: 0.1, chorusMix: 0.06, delayTime: 0.24, delayFeedback: 0.22, phaserMix: 0 },
    drawShape: sh("step", { dest: "cutoff", mode: "loop", time: 2, depth: 0.4, from: 0 }),
  }),
  P("Sequence", "v57-warp-seq", "Warp Seq", {
    osc1: { wave: "wt", table: "digital", pwm: 0.4, level: 0.8 },
    osc2: { wave: "sawtooth", fine: 6, level: 0.3 },
    arp: { on: true, hold: true, mode: "updown", rate: "1/8t", octaves: 2, gate: 0.42, swing: 0, tempo: 120 },
    fx: { delayMix: 0.2, reverbMix: 0.16, chorusMix: 0.1, delayTime: 0.28, delayFeedback: 0.3, phaserMix: 0.12 },
    drawShape: sh("warp", { dest: "pwm", dest2: "amp", mode: "loop", time: 1.6, depth: 0.6, from: 0 }),
  }),

  P("Keys", "v57-dual-ep", "Dual LFO EP", {
    osc1: { wave: "sine", level: 0.78 },
    osc2: { wave: "triangle", octave: 1, fine: 4, level: 0.32 },
    fmIndex: 0.18,
    noiseLevel: 0.04,
    lfo: { rate: 5.4, depth: 0.08, dest: "pitch", wave: "sine" },
    lfo2: { rate: 0.18, depth: 0.16, dest: "pan", wave: "sine" },
    ampEnv: { attack: 0.005, decay: 0.5, sustain: 0.48, release: 0.42 },
    fx: { delayMix: 0.08, reverbMix: 0.24, chorusMix: 0.22, delayTime: 0.3, delayFeedback: 0.16, phaserMix: 0.04 },
  }),
  P("Keys", "v57-table-organ", "Table Organ", {
    osc1: { wave: "wt", table: "organ", pwm: 0.2, level: 0.8 },
    osc2: { wave: "wt", table: "organ", pwm: 0.55, octave: 1, level: 0.35 },
    lfo: { rate: 0.12, depth: 0.1, dest: "cutoff" },
    lfo2: { rate: 6.8, depth: 0.04, dest: "amp" },
    fx: { delayMix: 0.06, reverbMix: 0.28, chorusMix: 0.16, delayTime: 0.36, delayFeedback: 0.14, phaserMix: 0 },
  }),
  P("Keys", "v57-clav-snap", "Clav Snap", {
    osc1: { wave: "pulse", pwm: 0.18, level: 0.88 },
    osc2: { wave: "sawtooth", octave: 1, level: 0.18 },
    noiseLevel: 0.06,
    velFilt: 0.55,
    ampEnv: { attack: 0.002, decay: 0.16, sustain: 0.22, release: 0.12 },
    fx: { delayMix: 0.08, reverbMix: 0.1, chorusMix: 0.04, delayTime: 0.22, delayFeedback: 0.12, phaserMix: 0 },
    drawShape: sh("snap", { dest: "amp", time: 0.35, depth: 0.7, from: 0 }),
  }),
  P("Keys", "v57-soft-tine", "Soft Tine", {
    osc1: { wave: "sine", level: 0.75 },
    osc2: { wave: "triangle", octave: 2, level: 0.22 },
    fmIndex: 0.14,
    ampEnv: { attack: 0.008, decay: 0.6, sustain: 0.4, release: 0.5 },
    fx: { delayMix: 0.08, reverbMix: 0.26, chorusMix: 0.18, delayTime: 0.32, delayFeedback: 0.16, phaserMix: 0.04 },
    drawShape: sh("silk", { dest: "amp", time: 1.2, depth: 0.4 }),
  }),
  P("Keys", "v57-house-fifth", "House Fifth", {
    osc1: { wave: "sawtooth", level: 0.82 },
    osc2: { wave: "sawtooth", semitone: 7, level: 0.55 },
    ampEnv: { attack: 0.004, decay: 0.22, sustain: 0.45, release: 0.22 },
    fx: { delayMix: 0.12, reverbMix: 0.14, chorusMix: 0.2, delayTime: 0.26, delayFeedback: 0.2, phaserMix: 0.06 },
  }),
  P("Keys", "v57-phaser-keys", "Phaser Keys", {
    osc1: { wave: "sawtooth", level: 0.7 },
    osc2: { wave: "square", pwm: 0.42, fine: 6, level: 0.48 },
    lfo: { rate: 0.18, depth: 0.12, dest: "cutoff" },
    fx: { delayMix: 0.1, reverbMix: 0.18, chorusMix: 0.12, delayTime: 0.34, delayFeedback: 0.2, phaserMix: 0.36 },
  }),
  P("Keys", "v57-dry-poly", "Dry Poly", {
    osc1: { wave: "sawtooth", level: 0.78 },
    osc2: { wave: "triangle", fine: 5, level: 0.45 },
    ampEnv: { attack: 0.006, decay: 0.3, sustain: 0.6, release: 0.28 },
    fx: { delayMix: 0.04, reverbMix: 0.08, chorusMix: 0.1, delayTime: 0.24, delayFeedback: 0.1, phaserMix: 0 },
  }),

  P("Pluck", "v57-pluck-fall", "Pluck Fall", {
    osc1: { wave: "triangle", level: 0.85 },
    osc2: { wave: "sine", octave: 1, level: 0.25 },
    ampEnv: { attack: 0.002, decay: 0.28, sustain: 0.08, release: 0.22 },
    fx: { delayMix: 0.16, reverbMix: 0.16, chorusMix: 0.06, delayTime: 0.28, delayFeedback: 0.22, phaserMix: 0 },
    drawShape: sh("fall", { dest: "cutoff", time: 0.55, depth: 0.65, from: 0 }),
  }),
  P("Bell", "v57-bell-spike", "Bell Spike", {
    osc1: { wave: "wt", table: "bell", pwm: 0.25, level: 0.72 },
    osc2: { wave: "sine", octave: 2, level: 0.35 },
    fmIndex: 0.2,
    ampEnv: { attack: 0.001, decay: 1.1, sustain: 0.12, release: 0.9 },
    fx: { delayMix: 0.14, reverbMix: 0.38, chorusMix: 0.06, delayTime: 0.4, delayFeedback: 0.18, phaserMix: 0.06 },
    drawShape: sh("spike", { dest: "amp", time: 0.9, depth: 0.5, from: 0 }),
  }),
  P("Pluck", "v57-crystal-gate", "Crystal Gate", {
    osc1: { wave: "wt", table: "glass", pwm: 0.4, level: 0.78 },
    osc2: { wave: "triangle", octave: 2, level: 0.22 },
    ampEnv: { attack: 0.003, decay: 0.4, sustain: 0.15, release: 0.35 },
    fx: { delayMix: 0.2, reverbMix: 0.28, chorusMix: 0.08, delayTime: 0.32, delayFeedback: 0.24, phaserMix: 0.08 },
    drawShape: sh("gate", { dest: "amp", mode: "loop", time: 0.6, depth: 0.45, from: 0 }),
  }),
  P("Pluck", "v57-mbira-glow", "Mbira Glow", {
    osc1: { wave: "sine", octave: 1, level: 0.7 },
    osc2: { wave: "triangle", octave: 2, fine: 6, level: 0.4 },
    fmIndex: 0.12,
    ampEnv: { attack: 0.002, decay: 0.7, sustain: 0.12, release: 0.5 },
    fx: { delayMix: 0.12, reverbMix: 0.3, chorusMix: 0.1, delayTime: 0.36, delayFeedback: 0.18, phaserMix: 0 },
    drawShape: sh("glow", { dest: "amp", time: 1.4, depth: 0.35 }),
  }),

  P("FX", "v57-shape-riser", "Shape Riser", {
    osc1: { wave: "sawtooth", level: 0.5 },
    osc2: { wave: "triangle", octave: -1, level: 0.12 },
    noiseLevel: 0.45,
    filter: { type: "highpass", cutoff: 0.15, resonance: 0.3, envAmount: 0.5, slope: 12 },
    ampEnv: { attack: 0.05, decay: 0.2, sustain: 0.9, release: 1.2 },
    lfo: { rate: 0.12, depth: 0.2, dest: "res" },
    fx: { delayMix: 0.22, reverbMix: 0.4, chorusMix: 0.05, delayTime: 0.4, delayFeedback: 0.35, phaserMix: 0.18 },
    drawShape: sh("rush", { dest: "cutoff", dest2: "amp", time: 8, depth: 1 }),
  }),
  P("FX", "v57-wind-silk", "Wind Silk", {
    osc1: { wave: "sine", level: 0.15 },
    noiseLevel: 0.72,
    filter: { type: "bandpass", cutoff: 0.4, resonance: 0.45, envAmount: 0.3, slope: 12 },
    lfo: { rate: 0.14, depth: 0.35, dest: "cutoff", wave: "sine" },
    lfo2: { rate: 0.09, depth: 0.25, dest: "pan" },
    fx: { delayMix: 0.18, reverbMix: 0.5, chorusMix: 0.04, delayTime: 0.5, delayFeedback: 0.28, phaserMix: 0.12 },
    drawShape: sh("silk", { dest: "amp", time: 4, depth: 0.9 }),
  }),
  P("FX", "v57-glitch-gate", "Glitch Gate", {
    osc1: { wave: "wt", table: "grit", pwm: 0.4, level: 0.55 },
    noiseLevel: 0.4,
    ring: 0.18,
    ampEnv: { attack: 0.001, decay: 0.12, sustain: 0.5, release: 0.08 },
    fx: { delayMix: 0.28, reverbMix: 0.16, chorusMix: 0.04, delayTime: 0.18, delayFeedback: 0.4, phaserMix: 0.1 },
    drawShape: sh("gate", { dest: "amp", mode: "loop", time: 0.22, depth: 1, from: 0 }),
    arp: { on: true, hold: true, mode: "random", rate: "1/16t", octaves: 2, gate: 0.3, swing: 0, tempo: 140 },
  }),
  P("FX", "v57-drone-dip", "Drone Dip", {
    osc1: { wave: "sawtooth", octave: -1, level: 0.55 },
    osc2: { wave: "sawtooth", octave: -1, fine: 6, level: 0.55 },
    unison: { voices: 2, detune: 0.28, spread: 0.4 },
    ampEnv: { attack: 1.2, decay: 0.5, sustain: 0.9, release: 2.5 },
    lfo: { rate: 0.06, depth: 0.18, dest: "cutoff" },
    fx: { delayMix: 0.2, reverbMix: 0.42, chorusMix: 0.12, delayTime: 0.55, delayFeedback: 0.32, phaserMix: 0.22 },
    drawShape: sh("dip", { dest: "amp", mode: "loop", time: 6, depth: 0.4, from: 0 }),
  }),
  P("FX", "v57-alarm-trem", "Alarm Trem", {
    osc1: { wave: "square", pwm: 0.12, octave: 1, level: 0.7 },
    osc2: { wave: "pulse", pwm: 0.08, octave: 2, level: 0.35 },
    filter: { type: "bandpass", cutoff: 0.62, resonance: 0.4, envAmount: 0.2, slope: 12 },
    lfo: { rate: 8, depth: 0.15, dest: "pitch", wave: "square" },
    fx: { delayMix: 0.16, reverbMix: 0.2, chorusMix: 0, delayTime: 0.22, delayFeedback: 0.25, phaserMix: 0.08 },
    drawShape: sh("trem", { dest: "amp", mode: "loop", time: 0.35, depth: 0.7, from: 0 }),
  }),
  P("Strings", "v57-bow-silk", "Bow Silk", {
    osc1: { wave: "sawtooth", level: 0.62 },
    osc2: { wave: "sawtooth", fine: 8, level: 0.58 },
    unison: { voices: 2, detune: 0.14, spread: 0.5 },
    ampEnv: { attack: 0.45, decay: 0.6, sustain: 0.8, release: 2.2 },
    lfo: { rate: 0.08, depth: 0.1, dest: "cutoff" },
    lfo2: { rate: 0.14, depth: 0.16, dest: "pan" },
    fx: { delayMix: 0.1, reverbMix: 0.36, chorusMix: 0.34, delayTime: 0.4, delayFeedback: 0.18, phaserMix: 0.06 },
    drawShape: sh("silk", { dest: "amp", time: 3.8, depth: 0.85 }),
  }),
];
