import type { OscParams, Patch } from "./types";

export const osc = (over: Partial<OscParams> = {}): OscParams => ({
  wave: "sawtooth",
  octave: 0,
  semitone: 0,
  fine: 0,
  level: 0.8,
  pwm: 0.5,
  ...over,
});

export function patch(
  partial: Omit<Patch, "osc1" | "osc2"> & { osc1?: Partial<OscParams>; osc2?: Partial<OscParams> },
): Patch {
  const { osc1: o1, osc2: o2, ...rest } = partial;
  return {
    ...rest,
    osc1: osc(o1),
    osc2: osc({
      wave: "sawtooth",
      octave: 0,
      semitone: 0,
      fine: 7,
      level: 0,
      pwm: 0.5,
      ...o2,
    }),
  } as Patch;
}

export function clonePatch(p: Patch, over: Partial<Patch> = {}): Patch {
  return {
    ...p,
    ...over,
    osc1: { ...p.osc1, ...(over.osc1 ?? {}) },
    osc2: { ...p.osc2, ...(over.osc2 ?? {}) },
    filter: { ...p.filter, ...(over.filter ?? {}) },
    ampEnv: { ...p.ampEnv, ...(over.ampEnv ?? {}) },
    filterEnv: { ...p.filterEnv, ...(over.filterEnv ?? {}) },
    lfo: { ...p.lfo, ...(over.lfo ?? {}) },
    fx: { ...p.fx, ...(over.fx ?? {}) },
    unison: { ...p.unison, ...(over.unison ?? {}) },
    arp: { ...p.arp, ...(over.arp ?? {}) },
  };
}

type Draft = Omit<Patch, "id" | "name" | "category" | "osc1" | "osc2"> & {
  osc1?: Partial<OscParams>;
  osc2?: Partial<OscParams>;
};

const arpOff = {
  on: false,
  mode: "up" as const,
  rate: "1/16" as const,
  octaves: 1 as const,
  gate: 0.5,
  swing: 0,
  tempo: 120,
};

export const CATEGORY_ORDER = [
  "Template",
  "Bass",
  "Lead",
  "Keys",
  "Brass",
  "Pad",
  "Pluck",
  "Bell",
  "Sequence",
  "FX",
] as const;

const DEFAULTS: Record<string, Draft> = {
  Bass: {
    osc1: { wave: "sawtooth", octave: -1, level: 0.9 },
    osc2: { wave: "square", octave: -1, fine: 4, level: 0.32 },
    subLevel: 0.55,
    noiseLevel: 0,
    fmIndex: 0,
    drive: 0.22,
    filter: { type: "lowpass", slope: 24, cutoff: 0.34, resonance: 0.32, envAmount: 0.42, keyTrack: 0.15 },
    ampEnv: { attack: 0.006, decay: 0.26, sustain: 0.7, release: 0.16 },
    filterEnv: { attack: 0.004, decay: 0.2, sustain: 0.18, release: 0.12 },
    lfo: { rate: 0.12, depth: 0.08, dest: "cutoff", wave: "sine" },
    fx: { delayMix: 0.05, delayTime: 0.28, delayFeedback: 0.2, reverbMix: 0.06, chorusMix: 0 },
    unison: { voices: 1, detune: 0.06, spread: 0.15 },
    glide: 0.05,
    polyMode: "mono",
    master: 0.76,
    arp: { ...arpOff, tempo: 118 },
  },
  Lead: {
    osc1: { wave: "sawtooth", level: 0.88 },
    osc2: { wave: "square", fine: 5, level: 0.28, pwm: 0.34 },
    subLevel: 0.12,
    noiseLevel: 0,
    fmIndex: 0,
    drive: 0.18,
    filter: { type: "lowpass", slope: 12, cutoff: 0.62, resonance: 0.24, envAmount: 0.32, keyTrack: 0.28 },
    ampEnv: { attack: 0.02, decay: 0.22, sustain: 0.72, release: 0.28 },
    filterEnv: { attack: 0.02, decay: 0.24, sustain: 0.45, release: 0.2 },
    lfo: { rate: 4.8, depth: 0.1, dest: "pitch", wave: "sine" },
    fx: { delayMix: 0.22, delayTime: 0.3, delayFeedback: 0.32, reverbMix: 0.16, chorusMix: 0.18 },
    unison: { voices: 1, detune: 0.1, spread: 0.35 },
    glide: 0.06,
    polyMode: "mono",
    master: 0.68,
    arp: { ...arpOff, tempo: 118 },
  },
  Keys: {
    osc1: { wave: "pulse", pwm: 0.4, level: 0.8 },
    osc2: { wave: "sawtooth", octave: 1, fine: -5, level: 0.28 },
    subLevel: 0.1,
    noiseLevel: 0,
    fmIndex: 0,
    drive: 0.08,
    filter: { type: "lowpass", slope: 12, cutoff: 0.58, resonance: 0.16, envAmount: 0.32, keyTrack: 0.38 },
    ampEnv: { attack: 0.008, decay: 0.32, sustain: 0.55, release: 0.35 },
    filterEnv: { attack: 0.006, decay: 0.36, sustain: 0.38, release: 0.3 },
    lfo: { rate: 0.45, depth: 0.08, dest: "pitch", wave: "sine" },
    fx: { delayMix: 0.1, delayTime: 0.32, delayFeedback: 0.22, reverbMix: 0.22, chorusMix: 0.24 },
    unison: { voices: 1, detune: 0.08, spread: 0.3 },
    glide: 0,
    polyMode: "poly",
    master: 0.7,
    arp: arpOff,
  },
  Brass: {
    osc1: { wave: "sawtooth", level: 0.86 },
    osc2: { wave: "square", semitone: 7, level: 0.35, pwm: 0.4 },
    subLevel: 0.2,
    noiseLevel: 0.02,
    fmIndex: 0,
    drive: 0.2,
    filter: { type: "lowpass", slope: 12, cutoff: 0.52, resonance: 0.22, envAmount: 0.48, keyTrack: 0.18 },
    ampEnv: { attack: 0.05, decay: 0.2, sustain: 0.7, release: 0.22 },
    filterEnv: { attack: 0.04, decay: 0.18, sustain: 0.4, release: 0.16 },
    lfo: { rate: 0.25, depth: 0.06, dest: "cutoff", wave: "sine" },
    fx: { delayMix: 0.08, delayTime: 0.28, delayFeedback: 0.2, reverbMix: 0.14, chorusMix: 0.16 },
    unison: { voices: 2, detune: 0.1, spread: 0.45 },
    glide: 0.03,
    polyMode: "poly",
    master: 0.68,
    arp: arpOff,
  },
  Pad: {
    osc1: { wave: "sawtooth", level: 0.7 },
    osc2: { wave: "sawtooth", fine: 10, level: 0.68 },
    subLevel: 0.1,
    noiseLevel: 0.03,
    fmIndex: 0,
    drive: 0.08,
    filter: { type: "lowpass", slope: 24, cutoff: 0.48, resonance: 0.1, envAmount: 0.2, keyTrack: 0.25 },
    ampEnv: { attack: 0.55, decay: 0.8, sustain: 0.72, release: 1.8 },
    filterEnv: { attack: 0.7, decay: 1.0, sustain: 0.55, release: 2.0 },
    lfo: { rate: 0.1, depth: 0.16, dest: "cutoff", wave: "sine" },
    fx: { delayMix: 0.16, delayTime: 0.42, delayFeedback: 0.26, reverbMix: 0.4, chorusMix: 0.32 },
    unison: { voices: 2, detune: 0.18, spread: 0.7 },
    glide: 0,
    polyMode: "poly",
    master: 0.6,
    arp: { ...arpOff, tempo: 92 },
  },
  Pluck: {
    osc1: { wave: "sawtooth", level: 0.85 },
    osc2: { wave: "square", fine: 5, level: 0.38 },
    subLevel: 0.06,
    noiseLevel: 0.05,
    fmIndex: 0,
    drive: 0.14,
    filter: { type: "lowpass", slope: 24, cutoff: 0.55, resonance: 0.55, envAmount: 0.68, keyTrack: 0.42 },
    ampEnv: { attack: 0.004, decay: 0.22, sustain: 0.08, release: 0.18 },
    filterEnv: { attack: 0.002, decay: 0.18, sustain: 0.06, release: 0.14 },
    lfo: { rate: 0.4, depth: 0.05, dest: "cutoff", wave: "sine" },
    fx: { delayMix: 0.22, delayTime: 0.3, delayFeedback: 0.32, reverbMix: 0.2, chorusMix: 0.1 },
    unison: { voices: 1, detune: 0.08, spread: 0.3 },
    glide: 0,
    polyMode: "poly",
    master: 0.7,
    arp: arpOff,
  },
  Bell: {
    osc1: { wave: "sine", octave: 1, level: 0.72 },
    osc2: { wave: "sine", octave: 2, fine: 5, level: 0.38 },
    subLevel: 0,
    noiseLevel: 0.03,
    fmIndex: 0.48,
    drive: 0.04,
    filter: { type: "lowpass", slope: 12, cutoff: 0.76, resonance: 0.1, envAmount: 0.16, keyTrack: 0.2 },
    ampEnv: { attack: 0.004, decay: 1.3, sustain: 0.12, release: 1.0 },
    filterEnv: { attack: 0.01, decay: 0.55, sustain: 0.2, release: 0.7 },
    lfo: { rate: 0.2, depth: 0.06, dest: "pitch", wave: "sine" },
    fx: { delayMix: 0.2, delayTime: 0.38, delayFeedback: 0.22, reverbMix: 0.44, chorusMix: 0.08 },
    unison: { voices: 1, detune: 0.04, spread: 0.25 },
    glide: 0,
    polyMode: "poly",
    master: 0.64,
    arp: { ...arpOff, tempo: 96 },
  },
  Sequence: {
    osc1: { wave: "square", pwm: 0.32, level: 0.82 },
    osc2: { wave: "sawtooth", octave: 1, fine: 5, level: 0.38 },
    subLevel: 0.12,
    noiseLevel: 0,
    fmIndex: 0,
    drive: 0.14,
    filter: { type: "lowpass", slope: 24, cutoff: 0.5, resonance: 0.36, envAmount: 0.52, keyTrack: 0.25 },
    ampEnv: { attack: 0.004, decay: 0.12, sustain: 0.32, release: 0.08 },
    filterEnv: { attack: 0.002, decay: 0.1, sustain: 0.14, release: 0.08 },
    lfo: { rate: 0.35, depth: 0.12, dest: "cutoff", wave: "triangle" },
    fx: { delayMix: 0.3, delayTime: 0.25, delayFeedback: 0.38, reverbMix: 0.16, chorusMix: 0.1 },
    unison: { voices: 1, detune: 0.08, spread: 0.28 },
    glide: 0,
    polyMode: "poly",
    master: 0.68,
    arp: { on: true, mode: "up", rate: "1/16", octaves: 2, gate: 0.5, swing: 0.08, tempo: 124 },
  },
  FX: {
    osc1: { wave: "sine", level: 0.2 },
    osc2: { wave: "triangle", octave: -1, level: 0.15 },
    subLevel: 0,
    noiseLevel: 0.7,
    fmIndex: 0,
    drive: 0.1,
    filter: { type: "bandpass", slope: 12, cutoff: 0.42, resonance: 0.5, envAmount: 0.55, keyTrack: 0 },
    ampEnv: { attack: 0.12, decay: 0.7, sustain: 0.5, release: 0.9 },
    filterEnv: { attack: 0.35, decay: 1.0, sustain: 0.3, release: 1.0 },
    lfo: { rate: 0.15, depth: 0.4, dest: "cutoff", wave: "sawtooth" },
    fx: { delayMix: 0.28, delayTime: 0.4, delayFeedback: 0.42, reverbMix: 0.38, chorusMix: 0.06 },
    unison: { voices: 1, detune: 0, spread: 0.2 },
    glide: 0,
    polyMode: "poly",
    master: 0.58,
    arp: { ...arpOff, mode: "random", tempo: 90 },
  },
  Template: {
    osc1: { wave: "sawtooth", level: 0.85 },
    osc2: { wave: "sawtooth", fine: 8, level: 0.7 },
    subLevel: 0.15,
    noiseLevel: 0,
    fmIndex: 0,
    drive: 0.12,
    filter: { type: "lowpass", slope: 24, cutoff: 0.62, resonance: 0.18, envAmount: 0.28, keyTrack: 0.35 },
    ampEnv: { attack: 0.008, decay: 0.32, sustain: 0.55, release: 0.35 },
    filterEnv: { attack: 0.01, decay: 0.28, sustain: 0.35, release: 0.3 },
    lfo: { rate: 0.35, depth: 0.08, dest: "cutoff", wave: "sine" },
    fx: { delayMix: 0.12, delayTime: 0.28, delayFeedback: 0.28, reverbMix: 0.18, chorusMix: 0.16 },
    unison: { voices: 1, detune: 0.12, spread: 0.4 },
    glide: 0,
    polyMode: "poly",
    master: 0.72,
    arp: arpOff,
  },
};

type DeepPartial<T> = {
  [K in keyof T]?: T[K] extends object ? DeepPartial<T[K]> : T[K];
};

type Over = DeepPartial<Draft>;

export function P(category: string, id: string, name: string, over: Over = {}): Patch {
  const d = DEFAULTS[category] ?? DEFAULTS.Keys!;
  return patch({
    id,
    name,
    category,
    subLevel: over.subLevel ?? d.subLevel,
    noiseLevel: over.noiseLevel ?? d.noiseLevel,
    fmIndex: over.fmIndex ?? d.fmIndex,
    drive: over.drive ?? d.drive,
    glide: over.glide ?? d.glide,
    polyMode: over.polyMode ?? d.polyMode,
    master: over.master ?? d.master,
    osc1: { ...d.osc1, ...over.osc1 },
    osc2: { ...d.osc2, ...over.osc2 },
    filter: { ...d.filter, ...over.filter },
    ampEnv: { ...d.ampEnv, ...over.ampEnv },
    filterEnv: { ...d.filterEnv, ...over.filterEnv },
    lfo: { ...d.lfo, ...over.lfo },
    fx: { ...d.fx, ...over.fx },
    unison: { ...d.unison, ...over.unison },
    arp: { ...d.arp, ...over.arp },
  });
}
