import type { Patch } from "./types";
import { clonePatch, mx, patch } from "./patch-kit";
import { EXTRA_FACTORY } from "./factory-extra";
import { EXTRA_V43 } from "./factory-v43";
import { CATEGORY_ORDER } from "./patch-kit";

export { clonePatch, CATEGORY_ORDER };

const baseFx = {
  delayMix: 0.12,
  delayTime: 0.28,
  delayFeedback: 0.28,
  reverbMix: 0.18,
  chorusMix: 0.08,
  phaserMix: 0.06,
};

const ampPluck = { attack: 0.004, decay: 0.22, sustain: 0.05, release: 0.18 };
const ampPad = { attack: 0.55, decay: 0.8, sustain: 0.72, release: 1.8 };
const ampKeys = { attack: 0.008, decay: 0.32, sustain: 0.55, release: 0.35 };
const ampBass = { attack: 0.006, decay: 0.28, sustain: 0.7, release: 0.16 };

const CORE: Patch[] = [
  patch({
    id: "init",
    name: "Init Dual Saw",
    category: "Keys",
    osc1: { wave: "sawtooth", level: 0.85 },
    osc2: { wave: "sawtooth", fine: 8, level: 0.7 },
    subLevel: 0.15,
    noiseLevel: 0,
    fmIndex: 0,
    drive: 0.12,
    velFilt: 0.28,
    drift: 0.1,
    lfo2: { rate: 0.32, depth: 0.1, dest: "pan", wave: "sine" },
    matrix: mx(
      { src: "vel", dest: "cutoff", amount: 0.3 },
      { src: "lfo2", dest: "pan", amount: 0.14 },
      { src: "mod", dest: "cutoff", amount: 0.25 },
      { src: "at", dest: "cutoff", amount: 0.5 },
    ),
    filter: { type: "lowpass", slope: 24, cutoff: 0.62, resonance: 0.18, envAmount: 0.28, keyTrack: 0.35 },
    ampEnv: ampKeys,
    filterEnv: { attack: 0.01, decay: 0.28, sustain: 0.35, release: 0.3 },
    lfo: { rate: 0.35, depth: 0.08, dest: "cutoff", wave: "sine" },
    fx: { ...baseFx, chorusMix: 0.16, reverbMix: 0.14, phaserMix: 0.08 },
    unison: { voices: 1, detune: 0.12, spread: 0.4 },
    glide: 0,
    polyMode: "poly",
    master: 0.72,
    arp: { on: false, mode: "up", rate: "1/16", octaves: 1, gate: 0.55, swing: 0, tempo: 118 },
  }),
  patch({
    id: "sub-bass",
    name: "Sub Current",
    category: "Bass",
    osc1: { wave: "sawtooth", octave: -1, level: 0.9 },
    osc2: { wave: "square", octave: -1, fine: 4, level: 0.35 },
    subLevel: 0.7,
    noiseLevel: 0.02,
    fmIndex: 0,
    drive: 0.28,
    velFilt: 0.45,
    drift: 0.1,
    lfo2: { rate: 0.08, depth: 0.1, dest: "cutoff", wave: "sine" },
    matrix: mx(
      { src: "vel", dest: "cutoff", amount: 0.42 },
      { src: "mod", dest: "cutoff", amount: 0.4 },
      { src: "lfo2", dest: "cutoff", amount: 0.12 },
      { src: "fenv", dest: "res", amount: 0.1 },
    ),
    filter: { type: "lowpass", slope: 24, cutoff: 0.32, resonance: 0.42, envAmount: 0.45, keyTrack: 0.15 },
    ampEnv: ampBass,
    filterEnv: { attack: 0.004, decay: 0.22, sustain: 0.18, release: 0.14 },
    lfo: { rate: 0.12, depth: 0.06, dest: "cutoff", wave: "sine" },
    fx: { ...baseFx, delayMix: 0.04, reverbMix: 0.06, chorusMix: 0 },
    unison: { voices: 1, detune: 0.05, spread: 0.15 },
    glide: 0.04,
    polyMode: "mono",
    master: 0.78,
    arp: { on: false, mode: "up", rate: "1/16", octaves: 1, gate: 0.5, swing: 0, tempo: 118 },
  }),
  patch({
    id: "acid",
    name: "Acid Line",
    category: "Bass",
    osc1: { wave: "sawtooth", octave: -1, level: 1 },
    osc2: { wave: "square", octave: -1, level: 0.2, pwm: 0.28 },
    subLevel: 0.25,
    noiseLevel: 0,
    fmIndex: 0,
    drive: 0.38,
    velFilt: 0.55,
    drift: 0.06,
    lfo2: { rate: 0.15, depth: 0.1, dest: "res", wave: "triangle" },
    matrix: mx(
      { src: "vel", dest: "cutoff", amount: 0.5 },
      { src: "mod", dest: "cutoff", amount: 0.45 },
      { src: "lfo2", dest: "res", amount: 0.16 },
      { src: "fenv", dest: "cutoff", amount: 0.12 },
    ),
    filter: { type: "lowpass", slope: 24, cutoff: 0.28, resonance: 0.78, envAmount: 0.72, keyTrack: 0.2 },
    ampEnv: { attack: 0.004, decay: 0.18, sustain: 0.55, release: 0.1 },
    filterEnv: { attack: 0.002, decay: 0.16, sustain: 0.08, release: 0.08 },
    lfo: { rate: 0.2, depth: 0.04, dest: "cutoff", wave: "triangle" },
    fx: { delayMix: 0.18, delayTime: 0.22, delayFeedback: 0.32, reverbMix: 0.08, chorusMix: 0, phaserMix: 0 },
    unison: { voices: 1, detune: 0, spread: 0 },
    glide: 0.08,
    polyMode: "legato",
    master: 0.74,
    arp: { on: true, mode: "up", rate: "1/16", octaves: 1, gate: 0.62, swing: 0.08, tempo: 128 },
  }),
  patch({
    id: "warm-pad",
    name: "Warm Field",
    category: "Pad",
    osc1: { wave: "sawtooth", level: 0.72 },
    osc2: { wave: "sawtooth", fine: 11, level: 0.7, octave: 0 },
    subLevel: 0.12,
    noiseLevel: 0.04,
    fmIndex: 0,
    drive: 0.1,
    drift: 0.28,
    lfo2: { rate: 0.07, depth: 0.18, dest: "pan", wave: "sine" },
    matrix: mx(
      { src: "lfo2", dest: "pan", amount: 0.26 },
      { src: "lfo1", dest: "cutoff", amount: 0.12 },
      { src: "mod", dest: "cutoff", amount: 0.2 },
      { src: "vel", dest: "amp", amount: 0.12 },
    ),
    filter: { type: "lowpass", slope: 24, cutoff: 0.48, resonance: 0.12, envAmount: 0.22, keyTrack: 0.25 },
    ampEnv: ampPad,
    filterEnv: { attack: 0.7, decay: 1.1, sustain: 0.55, release: 2.2 },
    lfo: { rate: 0.08, depth: 0.18, dest: "cutoff", wave: "sine" },
    fx: { delayMix: 0.16, delayTime: 0.42, delayFeedback: 0.28, reverbMix: 0.42, chorusMix: 0.32, phaserMix: 0.18 },
    unison: { voices: 3, detune: 0.22, spread: 0.7 },
    glide: 0,
    polyMode: "poly",
    master: 0.62,
    arp: { on: false, mode: "up", rate: "1/8", octaves: 1, gate: 0.8, swing: 0, tempo: 92 },
  }),
  patch({
    id: "poly-keys",
    name: "Poly Keys",
    category: "Keys",
    osc1: { wave: "pulse", pwm: 0.38, level: 0.8 },
    osc2: { wave: "sawtooth", octave: 1, fine: -6, level: 0.28 },
    subLevel: 0.1,
    noiseLevel: 0,
    fmIndex: 0,
    drive: 0.08,
    velFilt: 0.42,
    drift: 0.08,
    lfo2: { rate: 0.4, depth: 0.12, dest: "pan", wave: "sine" },
    matrix: mx(
      { src: "vel", dest: "cutoff", amount: 0.36 },
      { src: "vel", dest: "amp", amount: 0.22 },
      { src: "lfo2", dest: "pan", amount: 0.16 },
      { src: "mod", dest: "cutoff", amount: 0.28 },
    ),
    filter: { type: "lowpass", slope: 12, cutoff: 0.58, resonance: 0.16, envAmount: 0.32, keyTrack: 0.4 },
    ampEnv: ampKeys,
    filterEnv: { attack: 0.006, decay: 0.4, sustain: 0.4, release: 0.35 },
    lfo: { rate: 0.55, depth: 0.1, dest: "pitch", wave: "sine" },
    fx: { ...baseFx, chorusMix: 0.28, reverbMix: 0.22, delayMix: 0.1, phaserMix: 0.08 },
    unison: { voices: 1, detune: 0.08, spread: 0.3 },
    glide: 0,
    polyMode: "poly",
    master: 0.7,
    arp: { on: false, mode: "up", rate: "1/16", octaves: 1, gate: 0.5, swing: 0, tempo: 110 },
  }),
  patch({
    id: "pluck",
    name: "Resonant Pluck",
    category: "Pluck",
    osc1: { wave: "sawtooth", level: 0.85 },
    osc2: { wave: "square", fine: 5, level: 0.4 },
    subLevel: 0.05,
    noiseLevel: 0.06,
    fmIndex: 0,
    drive: 0.16,
    velFilt: 0.52,
    lfo2: { rate: 0.42, depth: 0.1, dest: "pan", wave: "sine" },
    matrix: mx(
      { src: "vel", dest: "cutoff", amount: 0.48 },
      { src: "vel", dest: "amp", amount: 0.28 },
      { src: "mod", dest: "res", amount: 0.2 },
      { src: "lfo2", dest: "pan", amount: 0.08 },
    ),
    filter: { type: "lowpass", slope: 24, cutoff: 0.55, resonance: 0.62, envAmount: 0.7, keyTrack: 0.45 },
    ampEnv: ampPluck,
    filterEnv: { attack: 0.002, decay: 0.18, sustain: 0.05, release: 0.14 },
    lfo: { rate: 0.4, depth: 0.05, dest: "cutoff", wave: "sine" },
    fx: { delayMix: 0.22, delayTime: 0.3, delayFeedback: 0.34, reverbMix: 0.2, chorusMix: 0.1, phaserMix: 0.06 },
    unison: { voices: 1, detune: 0.1, spread: 0.35 },
    glide: 0,
    polyMode: "poly",
    master: 0.7,
    arp: { on: false, mode: "up", rate: "1/16", octaves: 2, gate: 0.4, swing: 0, tempo: 120 },
  }),
  patch({
    id: "lead",
    name: "Copper Lead",
    category: "Lead",
    osc1: { wave: "sawtooth", level: 0.9 },
    osc2: { wave: "square", semitone: 7, level: 0.22, pwm: 0.32 },
    subLevel: 0.18,
    noiseLevel: 0,
    fmIndex: 0.08,
    drive: 0.22,
    velFilt: 0.22,
    drift: 0.1,
    lfo2: { rate: 0.22, depth: 0.14, dest: "pan", wave: "triangle" },
    matrix: mx(
      { src: "vel", dest: "amp", amount: 0.26 },
      { src: "lfo2", dest: "pan", amount: 0.2 },
      { src: "mod", dest: "cutoff", amount: 0.3 },
      { src: "lfo1", dest: "pitch", amount: 0.08 },
    ),
    filter: { type: "lowpass", slope: 12, cutoff: 0.64, resonance: 0.28, envAmount: 0.3, keyTrack: 0.3 },
    ampEnv: { attack: 0.02, decay: 0.22, sustain: 0.72, release: 0.28 },
    filterEnv: { attack: 0.03, decay: 0.25, sustain: 0.45, release: 0.22 },
    lfo: { rate: 5.2, depth: 0.12, dest: "pitch", wave: "sine" },
    fx: { delayMix: 0.28, delayTime: 0.32, delayFeedback: 0.36, reverbMix: 0.16, chorusMix: 0.2, phaserMix: 0.12 },
    unison: { voices: 2, detune: 0.14, spread: 0.45 },
    glide: 0.07,
    polyMode: "mono",
    master: 0.68,
    arp: { on: false, mode: "up", rate: "1/8", octaves: 1, gate: 0.6, swing: 0, tempo: 118 },
  }),
  patch({
    id: "bells",
    name: "Glass Bells",
    category: "Bell",
    osc1: { wave: "sine", octave: 1, level: 0.7 },
    osc2: { wave: "sine", octave: 2, fine: 4, level: 0.35 },
    subLevel: 0,
    noiseLevel: 0.03,
    fmIndex: 0.55,
    drive: 0.04,
    velFilt: 0.2,
    drift: 0.08,
    lfo2: { rate: 0.2, depth: 0.1, dest: "pan", wave: "sine" },
    ring: 0.1,
    matrix: mx(
      { src: "vel", dest: "amp", amount: 0.16 },
      { src: "lfo2", dest: "pan", amount: 0.14 },
      { src: "mod", dest: "fm", amount: 0.22 },
      { src: "lfo1", dest: "pitch", amount: 0.06 },
    ),
    filter: { type: "lowpass", slope: 12, cutoff: 0.78, resonance: 0.1, envAmount: 0.15, keyTrack: 0.2 },
    ampEnv: { attack: 0.004, decay: 1.4, sustain: 0.12, release: 1.1 },
    filterEnv: { attack: 0.01, decay: 0.6, sustain: 0.2, release: 0.8 },
    lfo: { rate: 0.18, depth: 0.06, dest: "pitch", wave: "sine" },
    fx: { delayMix: 0.2, delayTime: 0.38, delayFeedback: 0.22, reverbMix: 0.46, chorusMix: 0.08, phaserMix: 0.08 },
    unison: { voices: 1, detune: 0.04, spread: 0.25 },
    glide: 0,
    polyMode: "poly",
    master: 0.66,
    arp: { on: false, mode: "up", rate: "1/8", octaves: 2, gate: 0.35, swing: 0, tempo: 96 },
  }),
  patch({
    id: "strings",
    name: "Tape Strings",
    category: "Strings",
    osc1: { wave: "sawtooth", level: 0.68 },
    osc2: { wave: "sawtooth", octave: 1, fine: 6, level: 0.48 },
    subLevel: 0.08,
    noiseLevel: 0.03,
    fmIndex: 0,
    drive: 0.06,
    drift: 0.26,
    lfo2: { rate: 0.08, depth: 0.14, dest: "pan", wave: "sine" },
    matrix: mx(
      { src: "lfo2", dest: "pan", amount: 0.22 },
      { src: "lfo1", dest: "pitch", amount: 0.08 },
      { src: "mod", dest: "cutoff", amount: 0.18 },
      { src: "vel", dest: "amp", amount: 0.1 },
    ),
    filter: { type: "lowpass", slope: 24, cutoff: 0.5, resonance: 0.08, envAmount: 0.18, keyTrack: 0.3 },
    ampEnv: { attack: 0.35, decay: 0.6, sustain: 0.8, release: 1.4 },
    filterEnv: { attack: 0.4, decay: 0.9, sustain: 0.6, release: 1.2 },
    lfo: { rate: 0.22, depth: 0.14, dest: "pitch", wave: "triangle" },
    fx: { delayMix: 0.12, delayTime: 0.36, delayFeedback: 0.2, reverbMix: 0.34, chorusMix: 0.4, phaserMix: 0.1 },
    unison: { voices: 2, detune: 0.18, spread: 0.65 },
    glide: 0.02,
    polyMode: "poly",
    master: 0.64,
    arp: { on: false, mode: "up", rate: "1/8", octaves: 1, gate: 0.7, swing: 0, tempo: 100 },
  }),
  patch({
    id: "stabs",
    name: "Night Stab",
    category: "Keys",
    osc1: { wave: "square", pwm: 0.42, level: 0.85 },
    osc2: { wave: "sawtooth", semitone: 12, level: 0.3 },
    subLevel: 0.22,
    noiseLevel: 0.02,
    fmIndex: 0,
    drive: 0.2,
    velFilt: 0.4,
    lfo2: { rate: 0.3, depth: 0.1, dest: "pan", wave: "sine" },
    matrix: mx(
      { src: "vel", dest: "cutoff", amount: 0.38 },
      { src: "vel", dest: "amp", amount: 0.22 },
      { src: "lfo2", dest: "pan", amount: 0.12 },
      { src: "mod", dest: "cutoff", amount: 0.25 },
    ),
    filter: { type: "lowpass", slope: 12, cutoff: 0.52, resonance: 0.3, envAmount: 0.48, keyTrack: 0.2 },
    ampEnv: { attack: 0.004, decay: 0.16, sustain: 0.28, release: 0.18 },
    filterEnv: { attack: 0.003, decay: 0.14, sustain: 0.2, release: 0.12 },
    lfo: { rate: 0.3, depth: 0.05, dest: "cutoff", wave: "sine" },
    fx: { delayMix: 0.24, delayTime: 0.26, delayFeedback: 0.3, reverbMix: 0.16, chorusMix: 0.22, phaserMix: 0.1 },
    unison: { voices: 2, detune: 0.1, spread: 0.5 },
    glide: 0,
    polyMode: "poly",
    master: 0.7,
    arp: { on: false, mode: "up", rate: "1/16", octaves: 1, gate: 0.45, swing: 0, tempo: 112 },
  }),
  patch({
    id: "arp-seq",
    name: "Lyra Arp",
    category: "Sequence",
    osc1: { wave: "square", pwm: 0.3, level: 0.82 },
    osc2: { wave: "sawtooth", octave: 1, fine: 5, level: 0.4 },
    subLevel: 0.12,
    noiseLevel: 0,
    fmIndex: 0,
    drive: 0.14,
    velFilt: 0.3,
    lfo2: { rate: 0.5, depth: 0.12, dest: "res", wave: "triangle" },
    matrix: mx(
      { src: "lfo2", dest: "res", amount: 0.18 },
      { src: "vel", dest: "cutoff", amount: 0.28 },
      { src: "mod", dest: "cutoff", amount: 0.35 },
      { src: "lfo1", dest: "pan", amount: 0.12 },
    ),
    filter: { type: "lowpass", slope: 24, cutoff: 0.5, resonance: 0.38, envAmount: 0.55, keyTrack: 0.25 },
    ampEnv: { attack: 0.004, decay: 0.12, sustain: 0.35, release: 0.08 },
    filterEnv: { attack: 0.002, decay: 0.1, sustain: 0.15, release: 0.08 },
    lfo: { rate: 0.4, depth: 0.12, dest: "cutoff", wave: "triangle" },
    fx: { delayMix: 0.32, delayTime: 0.25, delayFeedback: 0.4, reverbMix: 0.18, chorusMix: 0.12, phaserMix: 0.08 },
    unison: { voices: 1, detune: 0.08, spread: 0.3 },
    glide: 0,
    polyMode: "poly",
    master: 0.68,
    arp: { on: true, mode: "updown", rate: "1/16", octaves: 2, gate: 0.5, swing: 0.12, tempo: 126 },
  }),
  patch({
    id: "air",
    name: "Air Current",
    category: "Pad",
    osc1: { wave: "triangle", octave: 1, level: 0.55 },
    osc2: { wave: "sine", octave: 2, fine: 9, level: 0.3 },
    subLevel: 0,
    noiseLevel: 0.22,
    fmIndex: 0.12,
    drive: 0.02,
    drift: 0.32,
    lfo2: { rate: 0.09, depth: 0.2, dest: "pan", wave: "sine" },
    matrix: mx(
      { src: "lfo2", dest: "pan", amount: 0.28 },
      { src: "lfo1", dest: "cutoff", amount: 0.16 },
      { src: "mod", dest: "res", amount: 0.22 },
      { src: "vel", dest: "amp", amount: 0.1 },
    ),
    filter: { type: "highpass", slope: 12, cutoff: 0.42, resonance: 0.18, envAmount: 0.2, keyTrack: 0.1 },
    ampEnv: { attack: 0.8, decay: 1.2, sustain: 0.65, release: 2.4 },
    filterEnv: { attack: 1.1, decay: 1.4, sustain: 0.5, release: 2 },
    lfo: { rate: 0.06, depth: 0.22, dest: "cutoff", wave: "sine" },
    fx: { delayMix: 0.18, delayTime: 0.5, delayFeedback: 0.26, reverbMix: 0.52, chorusMix: 0.18, phaserMix: 0.22 },
    unison: { voices: 2, detune: 0.16, spread: 0.8 },
    glide: 0,
    polyMode: "poly",
    master: 0.6,
    arp: { on: false, mode: "random", rate: "1/8", octaves: 2, gate: 0.7, swing: 0, tempo: 80 },
  }),
  patch({
    id: "supersaw",
    name: "Stack Saw",
    category: "Lead",
    osc1: { wave: "supersaw", level: 0.78 },
    osc2: { wave: "supersaw", fine: 6, level: 0.4 },
    subLevel: 0.1,
    noiseLevel: 0,
    fmIndex: 0,
    drive: 0.18,
    drift: 0.12,
    lfo2: { rate: 0.2, depth: 0.12, dest: "pan", wave: "triangle" },
    matrix: mx(
      { src: "lfo2", dest: "pan", amount: 0.18 },
      { src: "mod", dest: "cutoff", amount: 0.28 },
      { src: "vel", dest: "amp", amount: 0.2 },
      { src: "lfo1", dest: "cutoff", amount: 0.1 },
    ),
    filter: { type: "lowpass", slope: 24, cutoff: 0.6, resonance: 0.2, envAmount: 0.25, keyTrack: 0.3 },
    ampEnv: { attack: 0.05, decay: 0.3, sustain: 0.75, release: 0.4 },
    filterEnv: { attack: 0.04, decay: 0.35, sustain: 0.5, release: 0.3 },
    lfo: { rate: 0.28, depth: 0.1, dest: "cutoff", wave: "sine" },
    fx: { delayMix: 0.14, delayTime: 0.3, delayFeedback: 0.24, reverbMix: 0.2, chorusMix: 0.36, phaserMix: 0.12 },
    unison: { voices: 1, detune: 0.2, spread: 0.55 },
    glide: 0.03,
    polyMode: "poly",
    master: 0.62,
    arp: { on: false, mode: "up", rate: "1/8", octaves: 1, gate: 0.55, swing: 0, tempo: 118 },
  }),
  patch({
    id: "noise-fx",
    name: "Noise Sweep",
    category: "FX",
    osc1: { wave: "sine", level: 0.15 },
    osc2: { wave: "triangle", octave: -1, level: 0.1 },
    subLevel: 0,
    noiseLevel: 0.85,
    fmIndex: 0,
    drive: 0.1,
    ring: 0.16,
    drift: 0.28,
    velFilt: 0.12,
    lfo2: { rate: 0.11, depth: 0.28, dest: "pan", wave: "triangle" },
    matrix: mx(
      { src: "lfo2", dest: "pan", amount: 0.32 },
      { src: "lfo1", dest: "cutoff", amount: 0.28 },
      { src: "mod", dest: "res", amount: 0.35 },
      { src: "vel", dest: "amp", amount: 0.18 },
    ),
    filter: { type: "bandpass", slope: 12, cutoff: 0.4, resonance: 0.55, envAmount: 0.65, keyTrack: 0 },
    ampEnv: { attack: 0.15, decay: 0.8, sustain: 0.5, release: 0.9 },
    filterEnv: { attack: 0.4, decay: 1.2, sustain: 0.3, release: 1 },
    lfo: { rate: 0.15, depth: 0.45, dest: "cutoff", wave: "sawtooth" },
    fx: { delayMix: 0.3, delayTime: 0.4, delayFeedback: 0.45, reverbMix: 0.4, chorusMix: 0.05, phaserMix: 0.28 },
    unison: { voices: 1, detune: 0, spread: 0.2 },
    glide: 0,
    polyMode: "poly",
    master: 0.58,
    arp: { on: false, mode: "random", rate: "1/8", octaves: 1, gate: 0.8, swing: 0, tempo: 90 },
  }),
];

export const FACTORY: Patch[] = [...CORE, ...EXTRA_FACTORY, ...EXTRA_V43];

export const INIT_PATCH = clonePatch(FACTORY[0]!);

export function groupByCategory(patches: Patch[]): { category: string; patches: Patch[] }[] {
  const map = new Map<string, Patch[]>();
  for (const p of patches) {
    const list = map.get(p.category) ?? [];
    list.push(p);
    map.set(p.category, list);
  }
  const known = CATEGORY_ORDER.filter((c) => map.has(c)).map((c) => ({
    category: c,
    patches: map.get(c)!,
  }));
  const extra = [...map.keys()]
    .filter((c) => !CATEGORY_ORDER.includes(c as (typeof CATEGORY_ORDER)[number]))
    .sort()
    .map((c) => ({ category: c, patches: map.get(c)! }));
  return [...known, ...extra];
}
