import type { LfoParams, ModRoute, OscParams, Patch } from "./types";

export const osc = (over: Partial<OscParams> = {}): OscParams => ({
  wave: "sawtooth",
  octave: 0,
  semitone: 0,
  fine: 0,
  level: 0.8,
  pwm: 0.5,
  ...over,
});

export const defaultLfo2 = (): LfoParams => ({
  rate: 0.35,
  depth: 0,
  dest: "pan",
  wave: "triangle",
});

export const emptyMatrix = (): ModRoute[] => [
  { src: "lfo1", dest: "cutoff", amount: 0 },
  { src: "lfo2", dest: "pitch", amount: 0 },
  { src: "fenv", dest: "cutoff", amount: 0 },
  { src: "vel", dest: "amp", amount: 0 },
];

export const mx = (
  a: ModRoute,
  b: ModRoute,
  c: ModRoute,
  d: ModRoute,
): ModRoute[] => [a, b, c, d];

type PatchIn = Omit<Partial<Patch>, "osc1" | "osc2" | "fx" | "lfo2" | "matrix"> & {
  id: string;
  name: string;
  category: string;
  osc1?: Partial<OscParams>;
  osc2?: Partial<OscParams>;
  fx?: Partial<Patch["fx"]>;
  lfo2?: Partial<LfoParams>;
  matrix?: ModRoute[];
};

export function patch(partial: PatchIn): Patch {
  const { osc1: o1, osc2: o2, ...rest } = partial;
  return normalizePatch({
    subLevel: 0.1,
    noiseLevel: 0,
    fmIndex: 0,
    ring: 0,
    sync: 0,
    drift: 0,
    velFilt: 0,
    drive: 0.1,
    filter: { type: "lowpass", slope: 24, cutoff: 0.55, resonance: 0.18, envAmount: 0.25, keyTrack: 0.3 },
    ampEnv: { attack: 0.01, decay: 0.25, sustain: 0.65, release: 0.25 },
    filterEnv: { attack: 0.01, decay: 0.22, sustain: 0.3, release: 0.2 },
    lfo: { rate: 0.35, depth: 0.08, dest: "cutoff", wave: "sine" },
    lfo2: defaultLfo2(),
    matrix: emptyMatrix(),
    fx: { delayMix: 0.12, delayTime: 0.28, delayFeedback: 0.28, reverbMix: 0.18, chorusMix: 0.08, phaserMix: 0 },
    unison: { voices: 1, detune: 0.1, spread: 0.3 },
    glide: 0,
    polyMode: "poly",
    master: 0.7,
    arp: { on: false, mode: "up", rate: "1/16", octaves: 1, gate: 0.5, swing: 0, tempo: 120 },
    ...rest,
    osc1: osc(o1),
    osc2: osc({
      wave: "sawtooth",
      octave: 0,
      semitone: 0,
      fine: 7,
      level: 0,
      pwm: 0.5,
      ...o2,
    }),
  } as Patch);
}

export function normalizePatch(p: Patch): Patch {
  const matrixIn = Array.isArray(p.matrix) ? p.matrix : [];
  const matrix = emptyMatrix().map((slot, i) => {
    const r = matrixIn[i];
    if (!r) return slot;
    return {
      src: r.src ?? slot.src,
      dest: r.dest ?? slot.dest,
      amount: Number.isFinite(r.amount) ? r.amount : 0,
    };
  });
  return {
    ...p,
    ring: p.ring ?? 0,
    sync: p.sync ?? 0,
    drift: p.drift ?? 0,
    velFilt: p.velFilt ?? 0,
    lfo2: { ...defaultLfo2(), ...p.lfo2 },
    matrix,
    fx: {
      delayMix: p.fx?.delayMix ?? 0.12,
      delayTime: p.fx?.delayTime ?? 0.28,
      delayFeedback: p.fx?.delayFeedback ?? 0.28,
      reverbMix: p.fx?.reverbMix ?? 0.18,
      chorusMix: p.fx?.chorusMix ?? 0.08,
      phaserMix: p.fx?.phaserMix ?? 0,
    },
    osc1: osc(p.osc1),
    osc2: osc(p.osc2 ?? { level: 0 }),
  };
}

export function clonePatch(p: Patch, over: Partial<Patch> = {}): Patch {
  return normalizePatch({
    ...p,
    ...over,
    osc1: { ...p.osc1, ...(over.osc1 ?? {}) },
    osc2: { ...p.osc2, ...(over.osc2 ?? {}) },
    filter: { ...p.filter, ...(over.filter ?? {}) },
    ampEnv: { ...p.ampEnv, ...(over.ampEnv ?? {}) },
    filterEnv: { ...p.filterEnv, ...(over.filterEnv ?? {}) },
    lfo: { ...p.lfo, ...(over.lfo ?? {}) },
    lfo2: { ...defaultLfo2(), ...p.lfo2, ...(over.lfo2 ?? {}) },
    fx: { ...p.fx, phaserMix: p.fx?.phaserMix ?? 0, ...(over.fx ?? {}) },
    unison: { ...p.unison, ...(over.unison ?? {}) },
    arp: { ...p.arp, ...(over.arp ?? {}) },
    matrix: over.matrix ?? p.matrix,
    ring: over.ring ?? p.ring,
    sync: over.sync ?? p.sync,
    drift: over.drift ?? p.drift,
    velFilt: over.velFilt ?? p.velFilt,
  } as Patch);
}

type Draft = Omit<Patch, "id" | "name" | "category" | "osc1" | "osc2"> & {
  osc1?: Partial<OscParams>;
  osc2?: Partial<OscParams>;
};

const arpOff = {
  on: false,
  mode: "up" as const,
  rate: "1/16" as const,
  octaves: 1 as const,
  gate: 0.5,
  swing: 0,
  tempo: 120,
};

export const CATEGORY_ORDER = [
  "Bass",
  "Lead",
  "Keys",
  "Brass",
  "Strings",
  "Pad",
  "Pluck",
  "Bell",
  "Sequence",
  "Techno",
  "Drums",
  "FX",
] as const;

const v2 = {
  ring: 0,
  sync: 0,
  drift: 0,
  velFilt: 0,
  lfo2: defaultLfo2(),
  matrix: emptyMatrix(),
};

const DEFAULTS: Record<string, Draft> = {
  Bass: {
    osc1: { wave: "sawtooth", octave: -1, level: 0.9 },
    osc2: { wave: "square", octave: -1, fine: 4, level: 0.32 },
    subLevel: 0.55,
    noiseLevel: 0,
    fmIndex: 0,
    drive: 0.22,
    ...v2,
    velFilt: 0.4,
    drift: 0.08,
    lfo2: { rate: 0.07, depth: 0.1, dest: "cutoff", wave: "sine" },
    matrix: mx(
      { src: "vel", dest: "cutoff", amount: 0.4 },
      { src: "mod", dest: "cutoff", amount: 0.36 },
      { src: "lfo2", dest: "cutoff", amount: 0.14 },
      { src: "fenv", dest: "res", amount: 0.1 },
    ),
    filter: { type: "lowpass", slope: 24, cutoff: 0.34, resonance: 0.32, envAmount: 0.42, keyTrack: 0.15 },
    ampEnv: { attack: 0.006, decay: 0.26, sustain: 0.7, release: 0.16 },
    filterEnv: { attack: 0.004, decay: 0.2, sustain: 0.18, release: 0.12 },
    lfo: { rate: 0.12, depth: 0.08, dest: "cutoff", wave: "sine" },
    fx: { delayMix: 0.05, delayTime: 0.28, delayFeedback: 0.2, reverbMix: 0.06, chorusMix: 0, phaserMix: 0 },
    unison: { voices: 1, detune: 0.06, spread: 0.15 },
    glide: 0.05,
    polyMode: "mono",
    master: 0.76,
    arp: { ...arpOff, tempo: 118 },
  },
  Lead: {
    osc1: { wave: "sawtooth", level: 0.88 },
    osc2: { wave: "square", fine: 5, level: 0.28, pwm: 0.34 },
    subLevel: 0.12,
    noiseLevel: 0,
    fmIndex: 0,
    drive: 0.18,
    ...v2,
    velFilt: 0.22,
    drift: 0.1,
    lfo2: { rate: 0.25, depth: 0.14, dest: "pan", wave: "triangle" },
    matrix: mx(
      { src: "vel", dest: "amp", amount: 0.28 },
      { src: "lfo2", dest: "pan", amount: 0.22 },
      { src: "mod", dest: "cutoff", amount: 0.32 },
      { src: "lfo1", dest: "pitch", amount: 0.08 },
    ),
    filter: { type: "lowpass", slope: 12, cutoff: 0.62, resonance: 0.24, envAmount: 0.32, keyTrack: 0.28 },
    ampEnv: { attack: 0.02, decay: 0.22, sustain: 0.72, release: 0.28 },
    filterEnv: { attack: 0.02, decay: 0.24, sustain: 0.45, release: 0.2 },
    lfo: { rate: 4.8, depth: 0.1, dest: "pitch", wave: "sine" },
    fx: { delayMix: 0.22, delayTime: 0.3, delayFeedback: 0.32, reverbMix: 0.16, chorusMix: 0.18, phaserMix: 0.1 },
    unison: { voices: 1, detune: 0.1, spread: 0.35 },
    glide: 0.06,
    polyMode: "mono",
    master: 0.68,
    arp: { ...arpOff, tempo: 118 },
  },
  Keys: {
    osc1: { wave: "pulse", pwm: 0.4, level: 0.8 },
    osc2: { wave: "sawtooth", octave: 1, fine: -5, level: 0.28 },
    subLevel: 0.1,
    noiseLevel: 0,
    fmIndex: 0,
    drive: 0.08,
    ...v2,
    velFilt: 0.4,
    drift: 0.08,
    lfo2: { rate: 0.35, depth: 0.12, dest: "pan", wave: "sine" },
    matrix: mx(
      { src: "vel", dest: "cutoff", amount: 0.35 },
      { src: "vel", dest: "amp", amount: 0.22 },
      { src: "lfo2", dest: "pan", amount: 0.16 },
      { src: "mod", dest: "cutoff", amount: 0.28 },
    ),
    filter: { type: "lowpass", slope: 12, cutoff: 0.58, resonance: 0.16, envAmount: 0.32, keyTrack: 0.38 },
    ampEnv: { attack: 0.008, decay: 0.32, sustain: 0.55, release: 0.35 },
    filterEnv: { attack: 0.006, decay: 0.36, sustain: 0.38, release: 0.3 },
    lfo: { rate: 0.45, depth: 0.08, dest: "pitch", wave: "sine" },
    fx: { delayMix: 0.1, delayTime: 0.32, delayFeedback: 0.22, reverbMix: 0.22, chorusMix: 0.24, phaserMix: 0.08 },
    unison: { voices: 1, detune: 0.08, spread: 0.3 },
    glide: 0,
    polyMode: "poly",
    master: 0.7,
    arp: arpOff,
  },
  Brass: {
    osc1: { wave: "sawtooth", level: 0.86 },
    osc2: { wave: "square", semitone: 7, level: 0.35, pwm: 0.4 },
    subLevel: 0.2,
    noiseLevel: 0.02,
    fmIndex: 0,
    drive: 0.2,
    ...v2,
    velFilt: 0.38,
    drift: 0.1,
    lfo2: { rate: 0.18, depth: 0.1, dest: "pan", wave: "sine" },
    matrix: mx(
      { src: "vel", dest: "cutoff", amount: 0.42 },
      { src: "vel", dest: "amp", amount: 0.2 },
      { src: "lfo2", dest: "pan", amount: 0.14 },
      { src: "mod", dest: "cutoff", amount: 0.25 },
    ),
    filter: { type: "lowpass", slope: 12, cutoff: 0.52, resonance: 0.22, envAmount: 0.48, keyTrack: 0.18 },
    ampEnv: { attack: 0.05, decay: 0.2, sustain: 0.7, release: 0.22 },
    filterEnv: { attack: 0.04, decay: 0.18, sustain: 0.4, release: 0.16 },
    lfo: { rate: 0.25, depth: 0.06, dest: "cutoff", wave: "sine" },
    fx: { delayMix: 0.08, delayTime: 0.28, delayFeedback: 0.2, reverbMix: 0.14, chorusMix: 0.16, phaserMix: 0.08 },
    unison: { voices: 2, detune: 0.1, spread: 0.45 },
    glide: 0.03,
    polyMode: "poly",
    master: 0.68,
    arp: arpOff,
  },
  Strings: {
    osc1: { wave: "sawtooth", level: 0.68 },
    osc2: { wave: "sawtooth", octave: 1, fine: 6, level: 0.5 },
    subLevel: 0.08,
    noiseLevel: 0.02,
    fmIndex: 0,
    drive: 0.06,
    ...v2,
    drift: 0.22,
    velFilt: 0.18,
    matrix: mx(
      { src: "lfo2", dest: "pan", amount: 0.22 },
      { src: "lfo1", dest: "pitch", amount: 0.08 },
      { src: "mod", dest: "cutoff", amount: 0.2 },
      { src: "vel", dest: "amp", amount: 0.12 },
    ),
    filter: { type: "lowpass", slope: 24, cutoff: 0.5, resonance: 0.08, envAmount: 0.16, keyTrack: 0.28 },
    ampEnv: { attack: 0.4, decay: 0.7, sustain: 0.8, release: 1.5 },
    filterEnv: { attack: 0.45, decay: 0.9, sustain: 0.55, release: 1.3 },
    lfo: { rate: 0.22, depth: 0.1, dest: "pitch", wave: "triangle" },
    lfo2: { rate: 0.08, depth: 0.12, dest: "pan", wave: "sine" },
    fx: { delayMix: 0.12, delayTime: 0.38, delayFeedback: 0.2, reverbMix: 0.36, chorusMix: 0.48, phaserMix: 0.06 },
    unison: { voices: 2, detune: 0.16, spread: 0.62 },
    glide: 0.02,
    polyMode: "poly",
    master: 0.62,
    arp: { ...arpOff, tempo: 96 },
  },
  Pad: {
    osc1: { wave: "sawtooth", level: 0.7 },
    osc2: { wave: "sawtooth", fine: 10, level: 0.68 },
    subLevel: 0.1,
    noiseLevel: 0.03,
    fmIndex: 0,
    drive: 0.08,
    ...v2,
    drift: 0.24,
    velFilt: 0.16,
    lfo2: { rate: 0.08, depth: 0.16, dest: "pan", wave: "sine" },
    matrix: mx(
      { src: "lfo2", dest: "pan", amount: 0.24 },
      { src: "lfo1", dest: "cutoff", amount: 0.12 },
      { src: "mod", dest: "cutoff", amount: 0.22 },
      { src: "vel", dest: "amp", amount: 0.12 },
    ),
    filter: { type: "lowpass", slope: 24, cutoff: 0.48, resonance: 0.1, envAmount: 0.2, keyTrack: 0.25 },
    ampEnv: { attack: 0.55, decay: 0.8, sustain: 0.72, release: 1.8 },
    filterEnv: { attack: 0.7, decay: 1.0, sustain: 0.55, release: 2.0 },
    lfo: { rate: 0.1, depth: 0.16, dest: "cutoff", wave: "sine" },
    fx: { delayMix: 0.16, delayTime: 0.42, delayFeedback: 0.26, reverbMix: 0.4, chorusMix: 0.32, phaserMix: 0.16 },
    unison: { voices: 2, detune: 0.18, spread: 0.7 },
    glide: 0,
    polyMode: "poly",
    master: 0.6,
    arp: { ...arpOff, tempo: 92 },
  },
  Pluck: {
    osc1: { wave: "sawtooth", level: 0.85 },
    osc2: { wave: "square", fine: 5, level: 0.38 },
    subLevel: 0.06,
    noiseLevel: 0.05,
    fmIndex: 0,
    drive: 0.14,
    ...v2,
    velFilt: 0.5,
    lfo2: { rate: 0.4, depth: 0.08, dest: "pan", wave: "sine" },
    matrix: mx(
      { src: "vel", dest: "cutoff", amount: 0.45 },
      { src: "vel", dest: "amp", amount: 0.25 },
      { src: "lfo2", dest: "pan", amount: 0.1 },
      { src: "mod", dest: "res", amount: 0.18 },
    ),
    filter: { type: "lowpass", slope: 24, cutoff: 0.55, resonance: 0.55, envAmount: 0.68, keyTrack: 0.42 },
    ampEnv: { attack: 0.004, decay: 0.22, sustain: 0.08, release: 0.18 },
    filterEnv: { attack: 0.002, decay: 0.18, sustain: 0.06, release: 0.14 },
    lfo: { rate: 0.4, depth: 0.05, dest: "cutoff", wave: "sine" },
    fx: { delayMix: 0.22, delayTime: 0.3, delayFeedback: 0.32, reverbMix: 0.2, chorusMix: 0.1, phaserMix: 0.06 },
    unison: { voices: 1, detune: 0.08, spread: 0.3 },
    glide: 0,
    polyMode: "poly",
    master: 0.7,
    arp: arpOff,
  },
  Bell: {
    osc1: { wave: "sine", octave: 1, level: 0.72 },
    osc2: { wave: "sine", octave: 2, fine: 5, level: 0.38 },
    subLevel: 0,
    noiseLevel: 0.03,
    fmIndex: 0.48,
    drive: 0.04,
    ...v2,
    drift: 0.08,
    velFilt: 0.2,
    lfo2: { rate: 0.22, depth: 0.1, dest: "pan", wave: "sine" },
    matrix: mx(
      { src: "vel", dest: "amp", amount: 0.18 },
      { src: "lfo2", dest: "pan", amount: 0.16 },
      { src: "mod", dest: "fm", amount: 0.2 },
      { src: "lfo1", dest: "pitch", amount: 0.06 },
    ),
    filter: { type: "lowpass", slope: 12, cutoff: 0.76, resonance: 0.1, envAmount: 0.16, keyTrack: 0.2 },
    ampEnv: { attack: 0.004, decay: 1.3, sustain: 0.12, release: 1.0 },
    filterEnv: { attack: 0.01, decay: 0.55, sustain: 0.2, release: 0.7 },
    lfo: { rate: 0.2, depth: 0.06, dest: "pitch", wave: "sine" },
    fx: { delayMix: 0.2, delayTime: 0.38, delayFeedback: 0.22, reverbMix: 0.44, chorusMix: 0.08, phaserMix: 0.08 },
    unison: { voices: 1, detune: 0.04, spread: 0.25 },
    glide: 0,
    polyMode: "poly",
    master: 0.64,
    arp: { ...arpOff, tempo: 96 },
  },
  Sequence: {
    osc1: { wave: "square", pwm: 0.32, level: 0.82 },
    osc2: { wave: "sawtooth", octave: 1, fine: 5, level: 0.38 },
    subLevel: 0.12,
    noiseLevel: 0,
    fmIndex: 0,
    drive: 0.14,
    ...v2,
    velFilt: 0.28,
    lfo2: { rate: 0.5, depth: 0.12, dest: "res", wave: "triangle" },
    matrix: mx(
      { src: "lfo2", dest: "res", amount: 0.18 },
      { src: "vel", dest: "cutoff", amount: 0.3 },
      { src: "mod", dest: "cutoff", amount: 0.35 },
      { src: "lfo1", dest: "pan", amount: 0.12 },
    ),
    filter: { type: "lowpass", slope: 24, cutoff: 0.5, resonance: 0.36, envAmount: 0.52, keyTrack: 0.25 },
    ampEnv: { attack: 0.004, decay: 0.12, sustain: 0.32, release: 0.08 },
    filterEnv: { attack: 0.002, decay: 0.1, sustain: 0.14, release: 0.08 },
    lfo: { rate: 0.35, depth: 0.12, dest: "cutoff", wave: "triangle" },
    fx: { delayMix: 0.3, delayTime: 0.25, delayFeedback: 0.38, reverbMix: 0.16, chorusMix: 0.1, phaserMix: 0.08 },
    unison: { voices: 1, detune: 0.08, spread: 0.28 },
    glide: 0,
    polyMode: "poly",
    master: 0.68,
    arp: { on: true, mode: "up", rate: "1/16", octaves: 2, gate: 0.5, swing: 0.08, tempo: 124 },
  },
  Techno: {
    osc1: { wave: "sawtooth", octave: -1, level: 0.92 },
    osc2: { wave: "square", octave: -1, pwm: 0.3, level: 0.28 },
    subLevel: 0.42,
    noiseLevel: 0,
    fmIndex: 0,
    drive: 0.3,
    ...v2,
    velFilt: 0.32,
    drift: 0.06,
    matrix: mx(
      { src: "vel", dest: "cutoff", amount: 0.38 },
      { src: "mod", dest: "cutoff", amount: 0.45 },
      { src: "lfo2", dest: "cutoff", amount: 0.16 },
      { src: "fenv", dest: "res", amount: 0.12 },
    ),
    filter: { type: "lowpass", slope: 24, cutoff: 0.34, resonance: 0.58, envAmount: 0.6, keyTrack: 0.1 },
    ampEnv: { attack: 0.003, decay: 0.16, sustain: 0.48, release: 0.08 },
    filterEnv: { attack: 0.002, decay: 0.14, sustain: 0.1, release: 0.08 },
    lfo: { rate: 0.2, depth: 0.1, dest: "cutoff", wave: "triangle" },
    lfo2: { rate: 0.08, depth: 0.12, dest: "cutoff", wave: "sine" },
    fx: { delayMix: 0.14, delayTime: 0.23, delayFeedback: 0.3, reverbMix: 0.08, chorusMix: 0, phaserMix: 0.06 },
    unison: { voices: 1, detune: 0.08, spread: 0.18 },
    glide: 0.05,
    polyMode: "mono",
    master: 0.7,
    arp: { on: false, mode: "up", rate: "1/16", octaves: 1, gate: 0.42, swing: 0.08, tempo: 132 },
  },
  Drums: {
    osc1: { wave: "sine", octave: -1, level: 1 },
    osc2: { wave: "triangle", octave: 0, level: 0.25 },
    subLevel: 0.3,
    noiseLevel: 0.25,
    fmIndex: 0,
    drive: 0.18,
    ...v2,
    velFilt: 0.55,
    matrix: mx(
      { src: "vel", dest: "amp", amount: 0.4 },
      { src: "vel", dest: "cutoff", amount: 0.32 },
      { src: "mod", dest: "cutoff", amount: 0.2 },
      { src: "lfo1", dest: "cutoff", amount: 0 },
    ),
    filter: { type: "lowpass", slope: 12, cutoff: 0.4, resonance: 0.22, envAmount: 0.7, keyTrack: 0 },
    ampEnv: { attack: 0.002, decay: 0.18, sustain: 0.04, release: 0.12 },
    filterEnv: { attack: 0.001, decay: 0.12, sustain: 0.02, release: 0.08 },
    lfo: { rate: 0.2, depth: 0, dest: "cutoff", wave: "sine" },
    fx: { delayMix: 0.04, delayTime: 0.17, delayFeedback: 0.08, reverbMix: 0.1, chorusMix: 0, phaserMix: 0 },
    unison: { voices: 1, detune: 0, spread: 0 },
    glide: 0,
    polyMode: "mono",
    master: 0.72,
    arp: { ...arpOff, tempo: 132 },
  },
  FX: {
    osc1: { wave: "sine", level: 0.2 },
    osc2: { wave: "triangle", octave: -1, level: 0.15 },
    subLevel: 0,
    noiseLevel: 0.7,
    fmIndex: 0,
    drive: 0.1,
    ...v2,
    drift: 0.22,
    ring: 0.08,
    lfo2: { rate: 0.11, depth: 0.22, dest: "pan", wave: "triangle" },
    matrix: mx(
      { src: "lfo2", dest: "pan", amount: 0.28 },
      { src: "lfo1", dest: "cutoff", amount: 0.2 },
      { src: "mod", dest: "res", amount: 0.3 },
      { src: "vel", dest: "amp", amount: 0.15 },
    ),
    filter: { type: "bandpass", slope: 12, cutoff: 0.42, resonance: 0.5, envAmount: 0.55, keyTrack: 0 },
    ampEnv: { attack: 0.12, decay: 0.7, sustain: 0.5, release: 0.9 },
    filterEnv: { attack: 0.35, decay: 1.0, sustain: 0.3, release: 1.0 },
    lfo: { rate: 0.15, depth: 0.4, dest: "cutoff", wave: "sawtooth" },
    fx: { delayMix: 0.28, delayTime: 0.4, delayFeedback: 0.42, reverbMix: 0.38, chorusMix: 0.06, phaserMix: 0.2 },
    unison: { voices: 1, detune: 0, spread: 0.2 },
    glide: 0,
    polyMode: "poly",
    master: 0.58,
    arp: { ...arpOff, mode: "random", tempo: 90 },
  },
};

type DeepPartial<T> = {
  [K in keyof T]?: T[K] extends object ? DeepPartial<T[K]> : T[K];
};

type Over = DeepPartial<Draft>;

export function P(category: string, id: string, name: string, over: Over = {}): Patch {
  const d = DEFAULTS[category] ?? DEFAULTS.Keys!;
  return patch({
    id,
    name,
    category,
    subLevel: over.subLevel ?? d.subLevel,
    noiseLevel: over.noiseLevel ?? d.noiseLevel,
    fmIndex: over.fmIndex ?? d.fmIndex,
    ring: over.ring ?? d.ring,
    sync: over.sync ?? d.sync,
    drift: over.drift ?? d.drift,
    velFilt: over.velFilt ?? d.velFilt,
    drive: over.drive ?? d.drive,
    glide: over.glide ?? d.glide,
    polyMode: over.polyMode ?? d.polyMode,
    master: over.master ?? d.master,
    osc1: osc({ ...d.osc1, ...over.osc1 }),
    osc2: osc({ ...d.osc2, ...over.osc2 }),
    filter: { ...d.filter, ...over.filter },
    ampEnv: { ...d.ampEnv, ...over.ampEnv },
    filterEnv: { ...d.filterEnv, ...over.filterEnv },
    lfo: { ...d.lfo, ...over.lfo },
    lfo2: { ...d.lfo2, ...over.lfo2 },
    matrix: (over.matrix as ModRoute[] | undefined) ?? d.matrix,
    fx: { ...d.fx, ...over.fx },
    unison: { ...d.unison, ...over.unison },
    arp: { ...d.arp, ...over.arp },
  });
}
